[drape_frontend] New transit version in transit scheme renderer.
mapsme/omim pull request #13591
Opened 2020-08-22 08:23 UTC by mesozoic-drones

### Реквест про отрисовку слоя метро на новой версии транзитной секции.

- Методы для работы с данными в старом формате транзитной секции переименованы в методSubway.
- Добавлены похожие методы ля работы с новым форматом транзитной секции - методPT (public transport). 
- Для избежания копипасты один метод шаблонизирован (чтобы из него можно было вызывать методы для работы и со старой, и с новой версией).

Логика отрисовки линий новой версии: в рамках маршрута (route) есть от одной до нескольких линий (line). К каждой линии привязан отрезок полилинии (shapeLink), по которой эта линия пролегает: айди полилинии и индексы начальной и конечной точкек. Линии разных маршрутов на некоторых участках могут накладываться друг на друга, а нам нужно рисовать их параллельно. 

Для этого на этапе `gtfs_converter` для всех линий ищутся геометрически совпадающие отрезки. По каждому из таких отрезков проходит от двух линий. Для каждой из этих линий на отрезке рассчитывается ее порядок относительно других, чтобы в drape frontend рисовать их с правильными смещениями. Некоторые линии могут совпадать, но иметь разное направление. Условно ABCDE, EDCBA. Для таких полилиний нужно также правильно высчитывать смещение.

### Метро Сан-Франциско, мвм US_California_Santa_Clara_Palo Alto

1. В версии с метро лишний сегмент голубой линии, которого быть не должно. Это именно баг отрисовки, потому что  в данных голубая полилиния по этому отрезку пути не проходит. В версии с ОТ сегмент голубой линии отсутствует:

| Версия с метро  | Версия с ОТ |
| ------------- | ------------- |
| <img width="400" alt="image" src="https://user-images.githubusercontent.com/54934129/90640887-39dcb400-e239-11ea-984b-33f51311c932.png">  | <img width="512" alt="image" src="https://user-images.githubusercontent.com/54934129/90661612-16713380-e250-11ea-805f-5550f5e93471.png"> |

Тот же участок на схеме от яндекса:
<img width="471" alt="image" src="https://user-images.githubusercontent.com/54934129/90642130-adcb8c00-e23a-11ea-98bf-e1906c9f498d.png">

2. В версии ОТ участки линий между парами остановок, которые имеют одинаковую геометрию и одинаковый цвет, склеиваются в один. Это изменение одобрено Артемом Недогреевым и Катей Андреевой. Пример для метро Нью-Йорка:

| Одинаковые параллельные линии (версия с метро) | Отсутствуют одинаковые параллельные линии (версия с ОТ) |
| ------------- | ------------- |
| <img width="500" alt="image" src="https://user-images.githubusercontent.com/54934129/93335516-3c79fb80-f82f-11ea-8691-98b58f23c50b.png">  | <img width="500" alt="image" src="https://user-images.githubusercontent.com/54934129/93335551-4c91db00-f82f-11ea-9f81-18767ab08df1.png"> |
| <img width="500" alt="image" src="https://user-images.githubusercontent.com/54934129/93335757-95e22a80-f82f-11ea-9cb1-b73857d76079.png"> | <img width="500" alt="image" src="https://user-images.githubusercontent.com/54934129/93784045-2ad09380-fc35-11ea-915d-34d17b70e51f.png"> |

### Берлин
<img width="800" alt="image" src="https://user-images.githubusercontent.com/54934129/93336369-59fb9500-f830-11ea-8688-ec86912a53ec.png">
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/54934129/93880681-84dd6180-fce6-11ea-9abd-f3ad3cc04bcd.png">

### Фрагмент Берлина
<img width="800" alt="image" src="https://user-images.githubusercontent.com/54934129/93336586-a050f400-f830-11ea-95e9-5dd45d9aa096.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/54934129/93880541-5495c300-fce6-11ea-9f01-1c5a0a330707.png">

| Сан-Франциско целиком (версия с метро) |
| ------------- |
| <img width="1022" alt="Screenshot 2020-07-29 at 10 30 44" src="https://user-images.githubusercontent.com/54934129/90862504-2e52cf80-e396-11ea-97ff-d6a77048388a.png">  |

| Сан-Франциско целиком (версия с ОТ) |
| ------------- |
| <img width="904" alt="Screenshot 2020-08-21 at 10 06 40" src="https://user-images.githubusercontent.com/54934129/90862550-40347280-e396-11ea-8422-6daacbb13ce5.png"> |

| Нью-Йорк фрагмент (версия с метро) |
| ------------- |
|  <img width="1209" alt="NY_fragm_old" src="https://user-images.githubusercontent.com/54934129/93348226-9df59680-f83e-11ea-8abb-c231d98f8a35.png"> |

| Нью-Йорк фрагмент (версия с ОТ) |
| ------------- |
| <img width="1454" alt="image" src="https://user-images.githubusercontent.com/54934129/93855633-7a0fd600-fcc0-11ea-8940-76c399384eef.png"> |

2020-09-09 17:22 UTC, darina commented on drape_frontend/transit_scheme_builder.hpp
> +  ShapeInfo m_shapeInfo;
а почему теперь один ShapeInfo у остановки? остановка дублируется?

2020-09-09 17:22 UTC, darina commented on drape_frontend/transit_scheme_builder.hpp
> +    std::map<::transit::TransitId, StopNodeParamsPT> m_transfersPT;
сейчас может быть либо один набор данных, либо другой, так? Может, сделать два варианта структуры
MwmSchemeDataPT и
MwmSchemeDataSubway
и хранить их под optional в MwmSchemeData:
```
struct MwmSchemeData
{
  ::transit::TransitVersion m_transitVersion;
  std::optional<MwmSchemeDataPT> m_pt;
  std::optional<MwmSchemeDataSubway> m_subway;
};
```
и методы GenerateLines, CollectStops, CollectLines, CollectShapes, PrepareScheme перегрузить для разных типов MwmSchemeDataPT и MwmSchemeDataSubway

2020-09-09 17:22 UTC, darina commented on drape_frontend/transit_scheme_builder.hpp
> +      GenerateStop(context, stop.second, scheme.m_pivot, lines, batcher);
кажется, раз здесь шаблонный метод и ветки одинаковые, то if не нужен

2020-09-09 17:28 UTC, darina commented
>В версии с метро лишний сегмент голубой линии, которого быть не должно. Это именно баг отрисовки, потому что в данных голубая полилиния по этому отрезку пути не проходит. В версии с ОТ сегмент голубой линии отсутствует:

точно баг в отрисовке, а не в данных? в сторовской версии не вижу этой лишней голубой линии)

в версии с  OT почему-то поменялось относительное расположение голубой и зеленой веток после остановки LakeMerritt, для метро была логика по сортировке линий и распределении цветов по shape-ам так, чтобы относительный порядок не менялся. Возможно, тут линии логически разные (две голубые или две зеленые)?

2020-09-09 17:29 UTC, darina commented
>В версии ОТ чуть больше названий остановок, отображающихся на зуме 10. Это связано с тем, что алгоритм определения, является ли остановка "терминальной", отличается от варианта метро.

Для метро терминальной не считалась станция укороченной линии на маршруте, а теперь считается?

2020-09-14 06:46 UTC, mesozoic-drones commented on transit/transit_entities.hpp
> +                                                               "monorail"};
Да, информация про типы маршрутов метро нужна и на этапе генерации транзитной секции, и в дрейп фронтенде.

2020-09-14 07:25 UTC, mesozoic-drones commented
> > В версии ОТ чуть больше названий остановок, отображающихся на зуме 10. Это связано с тем, что алгоритм определения, является ли остановка "терминальной", отличается от варианта метро.
> 
> Для метро терминальной не считалась станция укороченной линии на маршруте, а теперь считается?

Да. Фактически это влияет только на количество названий станций, присутствующих на зуме 10.

2020-09-14 07:49 UTC, mesozoic-drones commented
> > В версии с метро лишний сегмент голубой линии, которого быть не должно. Это именно баг отрисовки, потому что в данных голубая полилиния по этому отрезку пути не проходит. В версии с ОТ сегмент голубой линии отсутствует:
> 
> точно баг в отрисовке, а не в данных? в сторовской версии не вижу этой лишней голубой линии)
> 
Я думаю, что это баг в отрисовке, но он проявился на сборке данных 200607 (в новых сборках нет). Почему мне кажется, что именно в отрисовке: если сконвертировать формат метро (на данных 200607) в ОТ и нарисовать голубую линию с большим промежутком, то видно, что у нее ответвления нет:

<img width="600" alt="Screenshot 2020-08-11 at 13 09 56" src="https://user-images.githubusercontent.com/54934129/93058072-88824000-f677-11ea-9070-0b534b508a9e.png">

Но при отрисовке в формате метро он появляется. Скрин данных 200607 в релизе:

<img width="600" alt="Screenshot 2020-08-11 at 13 09 56" src="https://user-images.githubusercontent.com/54934129/93058210-b9fb0b80-f677-11ea-879f-f48c712ec57c.jpeg">

2020-09-14 10:26 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +std::vector<TitleInfo> PlaceTitles(StopNodeParamsPT const & stopParams, float textSize,
Да, так меньше копипасты. Готово.

2020-09-14 10:30 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +}
Исправила здесь и еще в одном месте, где if состоит из одного return.

2020-09-14 10:41 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +        LineParams(transitDisplayInfo.m_routesPT.at(line.GetRouteId()).GetColor(), kBaseLineDepth);
Да. В версии метро она вычисляется по эвристике, а в версии ОТ - никак =) Мотивация: лучше организовать предрасчет глубины при подготовке mwm, чем тянуть его в рантайм. 

А при быстром расчете глубины в рантайме так или иначе проскакивают корнер-кейсы. Пример, где фиолетовую линию было бы логично расположить поверх остальных, потому что она совсем короткая:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/54934129/93076308-d0ad5c80-f68f-11ea-9400-e16287b84acd.png">

2020-09-14 11:04 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.hpp
> +      GenerateStop(context, stop.second, scheme.m_pivot, lines, batcher);
Пофиксила, спасибо)

2020-09-14 19:06 UTC, tomilov requested changes
В одних случаях используется `std::map::operator []`, в других -- `std::map::at`. Принцип какой когда -- неясен.

2020-09-15 07:12 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.hpp
> +  ShapeInfo m_shapeInfo;
Поменяла логику, теперь здесь вектор.

2020-09-15 07:13 UTC, mesozoic-drones commented
> В одних случаях используется `std::map::operator []`, в других -- `std::map::at`. Принцип какой когда -- неясен.

[] - для случаев, когда элемент может быть добавлен.
at() - для случаев, когда элемент гарантированно должен существовать.

2020-09-15 07:15 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +                        1.0f * static_cast<float>(linesCount % 2) + 1.0f;
Это не копирование, это оставление старого кода без изменения. Убрала)

2020-09-15 07:21 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +                          TV::TNormal(segment.m_rightNormal * halfWidth - offset, -halfWidth, 0.0),
Толя, это старый код, просто он вынесен в отдельный метод. Предлагаю это улучшение реализовать, но  в следующем реквесте про рефакторинг для повышения читаемости (и в него же докину другие твои предложения по рефакторингу). А этот реквест - про добавление работы с новой версией данных, не хотелось бы его усложнять дополнительными изменениями.

2020-09-15 07:21 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +      auto const end = ms::LatLon(52.549313637305999691, 13.414450707060183277);
У тебя старая версия реквеста, сейчас этой отладочной шняги уже нет.

2020-09-15 07:22 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +    titles[i].m_offset.y = currentOffset + titles[i].m_pixelSize.y / 2.0f;
https://github.com/mapsme/omim/pull/13591#discussion_r488442302

2020-09-15 07:26 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +      if (!handledStopIds.insert(stop1Id).second && !handledStopIds.insert(stop2Id).second)
Да, &&. Допустим, мы обрабатываем две остановки: stop1Id = 10, stop2Id = 11. Если мы уже обрабатывали stop2Id = 11 для другой линии, но не обрабатывали ее в паре с stop1Id = 10, то мы должны на данной итерации обработать обе эти остановки: найти  направление полилинии между ними и тд.

2020-09-15 07:30 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +
Это старый код, я его не трогала. Предлагаю сделать в следующем реквесте с рефакторином.

2020-09-15 07:33 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +void PlaceTitles(std::vector<TitleInfo> & titles, float textSize,
(Я не меняла название функции) Судя по всему, это и есть глагол: PlaceTitles = расположить названия, то есть задать им anchor, offset, и другие параметры, ответственные за расположение.

2020-09-15 07:50 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +    name.m_pixelSize = layout.GetPixelSize() + m2::PointF(4.0f * vs, 4.0f * vs);
Кто же знает) @darina Может, ты помнишь?

2020-09-15 09:36 UTC, mesozoic-drones commented
> Это стоит унести в cpp (без static), а здесь оставить extern std::unordered_set<std::string> const kSubwayLayerTypes;

transit_entities - это хедер без cpp. Можно просто убрать static, сделать inline.

2020-09-15 09:38 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +    std::vector<std::pair<dp::Color, routing::transit::LineId>> coloredLines;
Ты предлагаешь отрефакторить старый код. Мне ок, но в отдельном реквесте.

2020-09-15 09:39 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +    for (auto const & coloredLine : coloredLines)
В отдельном реквесте с рефакторингом.

2020-09-15 09:47 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +    title = transitDisplayInfo.m_features.at(featureId).m_title;
Я использую at() по принципу: этот элемент гарантированно существует и вероятность эксепшена минимальна; обращение к элементу по ключу - довольно частое, и замена at() на find() + assert() делает код более громоздким. Assert() в продовой версии отсутствует, а check() - слегка замедляет (в рендеринге нежелательно). 

Но на самом деле вопрос действительно спорный. Если считаешь, что с assert() надежнее, давай везде заменю на него.

2020-09-15 09:52 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.hpp
> +    std::map<::transit::TransitId, StopNodeParamsPT> m_transfersPT;
В таком формате как сейчас две версии уже присутствуют в генераторе, роутинге и транзите. Предлагаю оставить его для единообразия.

2020-09-15 10:21 UTC, tomilov commented on drape_frontend/transit_scheme_builder.cpp
> +    title = transitDisplayInfo.m_features.at(featureId).m_title;
Вопрос в том, что будет в логе, когда сработает std::terminate в `<map>` по необрабатываемому исключению в `std::map::at`? Удастся ли локализовать строку, где случилось непоправимое)?

2020-09-16 12:52 UTC, mesozoic-drones commented on transit/transit_entities.hpp
> +                                                               "monorail"};
transit_entities.hpp подключается в роутинге и еще в паре мест без линковки, было бы удобно оставить хедер-онли.

2020-09-16 12:57 UTC, mesozoic-drones commented
> в версии с OT почему-то поменялось относительное расположение голубой и зеленой веток после остановки LakeMerritt, для метро была логика по сортировке линий и распределении цветов по shape-ам так, чтобы относительный порядок не менялся. Возможно, тут линии логически разные (две голубые или две зеленые)?

Гляну, почему так. Расчет порядка расположения линий относительно друг друга теперь вынесен в препроцессинг до генератора. Сейчас там довольно простая логика сортировки цветов линий, и зеленая всегда должна быть выше (или ниже) голубой. Эта штука реализована в соседнем реквесте #13592

2020-09-16 13:03 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +    title = transitDisplayInfo.m_features.at(featureId).m_title;
Думаю, что удастся. Креши в отрисовке слоя метро удобны тем, что зная версию мвм и версию приложения, их можно гарантированно воспроизвести. Еще у нас в transit_scheme_builder.cpp встречаются асерты, которые работают только в дебаге, а в релизе превращаются в  обращение к `elem.end()->property`:

```
ASSERT(stop2It != transitDisplayInfo.m_stopsSubway.end(), (stop2Id));
auto const transfer2Id = stop2It->second.GetTransferId();
```

2020-09-16 13:05 UTC, mesozoic-drones commented
@darina @tomilov PTAL

2020-09-16 13:05 UTC, mesozoic-drones commented
JTALL

2020-09-16 14:25 UTC, tomilov commented on drape_frontend/transit_scheme_builder.cpp
> +    title = transitDisplayInfo.m_features.at(featureId).m_title;
`O(1)` ASSERT-ы можно превратить в CHECK-и, мне кажется, без значимого урона производительности.

2020-09-17 12:36 UTC, darina commented
>В версии ОТ участки линий между парами остановок, которые имеют одинаковую геометрию и одинаковый цвет, склеиваются в один.

Для информации, в свое время мы решили оставить на схеме несколько разных логических маршрутов одинакового цвета, потому что в этом есть своя информативность. Покажу на примере метро в Стокгольме. Наличие нескольких зеленых линий дает понять, что, например, до конечной Hasselby strand идет не любой поезд из центра. Все равно не понятно, как именно идет ветка от начала до конца, но человек хотя бы видит, что есть несколько вариантов, что может помочь избежать досадной ситуации.
![2020-09-17 15 24 33](https://user-images.githubusercontent.com/1092934/93470399-87147a00-f8fa-11ea-8efc-2aa40601fc5d.jpg)
![0_9b00d_bd413411_orig](https://user-images.githubusercontent.com/1092934/93470428-95629600-f8fa-11ea-9c7e-8369e16f6155.png)

В случае с ОТ ситуация выглядит потяжелее, конечно, стало больше одноцветных линий.

После выкидывания лишних линий что-то не так стало с маркерами, потому что их вид остался для случая, когда линий должно быть больше:
![image](https://user-images.githubusercontent.com/1092934/93470839-2df91600-f8fb-11ea-9eef-e03ff0073a1b.png)
![image](https://user-images.githubusercontent.com/1092934/93470879-40734f80-f8fb-11ea-8230-55c0f3419a84.png)
![image](https://user-images.githubusercontent.com/1092934/93470923-52ed8900-f8fb-11ea-96fc-39f4b91bc1fd.png)

2020-09-17 14:48 UTC, darina commented on drape_frontend/transit_scheme_builder.cpp
> +    titles[i].m_offset.y = currentOffset + titles[i].m_pixelSize.y / 2.0f;
вероятно, это к вопросу выше, что за увеличение на 4.0f вот здесь
`name.m_pixelSize = layout.GetPixelSize() + m2::PointF(4.0f * vs, 4.0f * vs);`
насколько помню, это чтобы несколько названий, расположенных подряд, имели между собой больше свободного места
![IMAGE 2020-09-17 17:48:11](https://user-images.githubusercontent.com/1092934/93487442-f5166c80-f90d-11ea-9b7f-a063dd284206.jpg)

2020-09-17 14:52 UTC, darina commented on drape_frontend/transit_scheme_builder.cpp
> +    name.m_pixelSize = layout.GetPixelSize() + m2::PointF(4.0f * vs, 4.0f * vs);
[ответила тут](https://github.com/mapsme/omim/pull/13591/files#r490311084)

2020-09-17 15:30 UTC, darina commented on drape_frontend/transit_scheme_builder.hpp
> +    std::map<::transit::TransitId, StopNodeParamsPT> m_transfersPT;
На ваше усмотрение, конечно. Предложила, чтобы было явно видно раздельное использование этих данных.

2020-09-17 15:30 UTC, darina commented on drape_frontend/transit_scheme_builder.hpp
> +  std::vector<ShapeInfo> m_shapeInfoOut;
это аналог информации из ShapeParams m_forwardLines и m_backwardLines? То есть попадание в in или в out зависит от порядка остановки по ходу полилинии из RouteSegment?

2020-09-17 15:30 UTC, darina commented on drape_frontend/transit_scheme_builder.cpp
> +        LineParams(transitDisplayInfo.m_routesPT.at(line.GetRouteId()).GetColor(), kBaseLineDepth);
С одинаковой глубиной они же тоже сейчас будут перекрываться в случайном порядке, только при этом разные сегменты одной линии могу быть то под, то над сегментами другой, смотря в каком порядке нарисуются. Я к тому, что инкремент можно оставить с TODO, раз лучшей замены пока нет.

2020-09-17 15:32 UTC, darina commented
>Почему мне кажется, что именно в отрисовке: если сконвертировать формат метро (на данных 200607) в ОТ и нарисовать голубую линию с большим промежутком, то видно, что у нее ответвления нет:

Сложно сказать, это мог быть и баг в данных, который отсеился при ковертации, но проскочил при отрисовке)

2020-09-17 16:40 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.hpp
> +  std::vector<ShapeInfo> m_shapeInfoOut;
Да, идея такая: в m_shapeInfoIn - все, что входит в остановку, в m_shapeInfoOut - то, что выходит.

2020-09-18 15:03 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +    name.m_pixelSize = layout.GetPixelSize() + m2::PointF(4.0f * vs, 4.0f * vs);
Спасибо, понятно!

2020-09-21 14:37 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +    title = transitDisplayInfo.m_features.at(featureId).m_title;
Готово: в новом коде все .at() заменила на .find() + CHECK().

2020-09-21 15:04 UTC, mesozoic-drones commented
> С одинаковой глубиной они же тоже сейчас будут перекрываться в случайном порядке, только при этом разные сегменты одной линии могу быть то под, то над сегментами другой, смотря в каком порядке нарисуются. Я к тому, что инкремент можно оставить с TODO, раз лучшей замены пока нет.

Готово, сделала генерацию линий с учетом глубины: теперь линии одного цвета находятся на одной глубине и например все синии линии будут отрисовываться поверх светло-голубых.

2020-09-21 15:14 UTC, mesozoic-drones commented
> После выкидывания лишних линий что-то не так стало с маркерами, потому что их вид остался для случая, когда линий должно быть больше

Исправила. Примечание: в этой версии стыки [зонного оборота поездов](https://ru.wikipedia.org/wiki/Арбатско-Покровская_линия#Зонный_оборот_поездов) за пересадки не считаются (как и на всех найденных мной картах). 

Пересадка рисуется в случаях: 

- через остановку проходит более одного цвета; 
- через остановку в одну сторону проходит более одной геометрии (например, две линии одного цвета, но под углом 20 градусов друг к другу);
- остановка явно привязана к пересадочному узлу через `transfers`.

2020-09-22 07:44 UTC, mesozoic-drones commented
@darina @tomilov PTAL

2020-09-22 14:33 UTC, darina commented on drape_frontend/transit_scheme_builder.cpp
> +
не удобнее ли сделать базовым метод, который работает с std::set<std::string> const & colors, и однократно находит m_direction и сразу вставляет все цвета?
в второй метод просто из одиночной строки std::string const & color формирует set и вызывает первый метод

2020-09-22 14:35 UTC, darina commented on drape_frontend/transit_scheme_builder.cpp
> +
еще константа eps = 1e-1 кажется довольно большой, это же должно быть полное совпадение, а тут возможны промахи

2020-09-22 14:50 UTC, darina commented on drape_frontend/transit_scheme_builder.cpp
> +
в целом, такой способ поиска shape выглядит ненадежным, если две дуги выходят из остановки в одном направлении, но потом меняют свою геометрию
![2020-09-22 17 42 16](https://user-images.githubusercontent.com/1092934/93897720-1656ce80-fcfb-11ea-9c90-9ed4782c2e7d.jpg)
или я неправильно поняла физический смысл?

2020-09-22 15:09 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +
Физический смысл такой: отрисовка линий и отрисовка пересадок/остановок между собой никак не связаны. Поиск shape для остановки никак не влияет на количество и цвет полилиний на карте. Поиск shape для остановки определяет то, будет ли остановка нарисована как пересадка, и если да, то насколько длинная.

Поэтому и eps = 1e-1  может быть довольно большим: нас интересует количество направлений линий, входящих/исходящих из остановки, которые визуально отличаются. 

На твоем примере с фотки: две правые дуги для этой остановки будут иметь один и тот же direction, но любом случае отрисуются обе.

2020-09-22 15:11 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +
> не удобнее ли сделать базовым метод, который работает с std::set<std::string> const & colors, и однократно находит m_direction и сразу вставляет все цвета?
Нам эта информация нужна в привязке к остановке. Кажется, удобно ее заполнять как раз в цикле по остановкам.

2020-09-22 15:27 UTC, darina commented on drape_frontend/transit_scheme_builder.cpp
> +
>Поиск shape для остановки определяет то, будет ли остановка нарисована как пересадка, и если да, то насколько длинная.
на длину пересадки ведь влияет максимальное количество разных цветов, приходящихся на один shape? то есть максимальное число параллельных линий, выходящий из остановки при отрисовке. Поэтому если цвет попадет в чужой shape, то этот максимум будет вычислен неверно?

2020-09-22 15:38 UTC, darina commented on drape_frontend/transit_scheme_builder.cpp
> +
>Нам эта информация нужна в привязке к остановке. Кажется, удобно ее заполнять как раз в цикле по остановкам.

Я имела ввиду почти ничего не менять, только передачу `std::set<std::string> const & colors` и` std::string const & color` в имеющихся методах

```
void UpdateShapeInfos(std::vector<ShapeInfoPT> & shapeInfos, m2::PointD const & newDir,
                      std::set<std::string> const & colors)
{
  static double constexpr eps = 1e-1;

  auto const newDirReverse = -newDir;

  for (ShapeInfoPT & info : shapeInfos)
  {
    if (base::AlmostEqualAbs(info.m_direction, newDir, eps) ||
        base::AlmostEqualAbs(info.m_direction, newDirReverse, eps))
    {
      for (auto const & color : colors)
        info.m_colors.insert(color);
      return;
    }
  }

  shapeInfos.push_back(ShapeInfoPT(newDir, colors));
}

void UpdateShapeInfos(std::vector<ShapeInfoPT> & shapeInfos, m2::PointD const & newDir,
                      std::string const & color)
{
  UpdateShapeInfos(shapeInfos, newDir, {color});
}
```

2020-09-22 15:39 UTC, darina approved these changes

2020-09-22 16:42 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +
> Поэтому если цвет попадет в чужой shape, то этот максимум будет вычислен неверно?

Да. Поэтому предлагаешь сделать eps поменьше?

2020-09-22 16:53 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +
> Я имела в виду почти ничего не менять, только передачу std::set<std::string> const & colors и std::string const & color в имеющихся методах

Сори, не так поняла. Сделала.

2020-09-22 17:55 UTC, mesozoic-drones commented
JTALL

2020-09-22 18:15 UTC, darina commented on drape_frontend/transit_scheme_builder.cpp
> +
>Да. Поэтому предлагаешь сделать eps поменьше?

Да, это должно улучшить ситуацию, хотя и не спасет от случая на картинке. Раньше был routing::transit::ShapeId, по которому однозначно адресовался ShapeInfo, сейчас не вижу, к чему можно привязаться.

2020-09-23 07:30 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +
Готово.
 В текущей схеме нам и не нужно уникально определять ShapeInfo в привязке к остановке. Для отрисовки линий мы используем m_routeSegmentsPT, а ShapeInfoPT::m_direction - только для прикидывания, какую пересадку рисовать (и рисовать ли вообще).

2020-09-23 20:49 UTC, tomilov commented
> transit_entities - это хедер без cpp. Можно просто убрать static, сделать inline.

Обязательно стоит так сделать.
А так вроде бы всё норм, насколько я могу понять. Собрал, запустил и посмотрел на десктопе Linux.

В некоторых местах вот такое наблюдаю, что этому причина?
![image](https://user-images.githubusercontent.com/896175/94064609-5bfebe80-fe03-11ea-8646-1182a5d82a8e.png)
И пересадки (я правильно называю?) имеют не совсем корректную ширину. Или это специально такой стиль?
![image](https://user-images.githubusercontent.com/896175/94064679-7a64ba00-fe03-11ea-9fb0-36811e44717e.png)
Эти две жёлтые линии никак между собой не связаны? Или коллизии допустимы?
![image](https://user-images.githubusercontent.com/896175/94065033-fe1ea680-fe03-11ea-838e-8fc961b99423.png)

2020-09-23 21:20 UTC, tomilov commented
На Android armeabi-v7a тоже посмотрел.

2020-09-24 08:31 UTC, tomilov commented
Можно было и `inline`, раз есть такая фича в языке удобная (как раз для этого случая), но и так сойдёт.

2020-09-24 08:32 UTC, tomilov approved these changes

2020-09-24 09:36 UTC, mesozoic-drones commented
> Эти две жёлтые линии никак между собой не связаны? Или коллизии допустимы?
Такая же отрисовка есть и в версии метро, это ок.

2020-09-24 09:39 UTC, mesozoic-drones commented
> В некоторых местах вот такое наблюдаю, что этому причина?

Это определенно косяк, но не этого реквеста, а другого, который подготавливает данные: #13592 Разберусь и исправлю там.

> И пересадки (я правильно называю?) имеют не совсем корректную ширину. Или это специально такой стиль?

А здесь возник косяк из-за странной обработки цвета "default". Предлагаю докинуть фикс в новом реквесте.

2020-09-24 09:41 UTC, merged