[transit][subway generator] Split lines into segments for rendering on the subway layer.
mapsme/omim pull request #13592
Opened 2020-08-22 08:28 UTC by mesozoic-drones

### О чем реквест
В этом реквесте реализованы изменения в конвертации старого формата метро в новый формат ОТ для корректного рендеринга секции ОТ на слое метро. Рендеринг реализован в замерженном реквесте #13591.

### Какие изменения потребовались и почему

**1. Разбиение линии маршрута на отрезки в зависимости от того, на каком из отрезков сколько имеется параллельных ей линий другого цвета. Сохранение этой информации в lines_metadata.transit.json** 

В формате метро у нас есть 1 большой json-файл с данными о метро по всему миру. В нем полилинии геометрии метро (shapes) не хранятся целиком: каждая линия (line) разбита на ребра (edges), и каждое ребро ссылается на соответствующий отрезок геометрии. Пример ребра, соединяющего две остановки на линии:

```json
        {
            "line_id": 79174371,
            "shape_ids": [
                {
                    "stop1_id": 2678030,
                    "stop2_id": 35859318
                }
            ],
            "stop1_id": 35859318,
            "stop2_id": 2678030,
            "transfer": false,
            "weight": 196
        },
```

Для новой версии транзитной секции мы отказались от разбиения полилиний маршрутов на минимальные отрезки "от остановки i - до остановки i+1". Теперь в данных хранится полилиния пути целиком, а отдельные линии маршрутов и ребра ссылаются на нее через shapeLink: id полилинии, индекс первой точки на ней и индекс последней точки. 

При таком подходе необходимо реализовать алгоритм, при котором параллельные отрезки разных линий не накладываются друг на друга при рендеринге, а имеют каждый свое смещение относительно оси симметрии:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/54934129/90952272-ddf97180-e46a-11ea-949f-2acf283de51b.png">

Решено эти расчеты унести в офлайн, на стадию препроцессинга метро и подмешивания его к gtfs-данным в результирующий json для генератора. Офлайновая составляющая позволит в будущем реализовать алгоритм расчитывания смещений линий так, чтобы минимизировать их пересечения на карте (в текущей реализации метро это невозможно). Полученные отрезки сохраняются в lines_metadata.transit.json. **Только линии, айди которых есть в этом файле (а далее - секции mwm), попадают на схему метро.**

Алгоритм добавлен в subway_converter.cpp `SubwayConverter::PrepareLinesMetadata()` и состоит из шагов:
1. Сортируем маршруты по цвету `GetLinesOnScheme(linesInRegion)`. Это нужно, чтобы для каждой линии маршрута знать ее индекс среди других линий. На схеме метро линии одного цвета не должны идти параллельно. 
<img width=600 src=https://user-images.githubusercontent.com/54934129/90952386-d1c1e400-e46b-11ea-8899-64ecfc0e674b.jpeg>

2. Находим пересекающиеся отрезки на линиях (цилк в `PrepareLinesMetadata()` после вызова `GetLinesOnScheme(linesInRegion)`. У каждой линии сохраняется набор отрезков и айди параллельных ей линий на этих отрезках.
<img width=600 src=https://user-images.githubusercontent.com/54934129/90952407-f1f1a300-e46b-11ea-8c4a-beace77d34c1.jpeg>

3. Зная отрезки, количество линий на отрезке и индекс данной линии среди других, можно расчитать ее порядок (приоритет) `CalculateLinePriorities(linesOnScheme)`. Порядок рассчитывается так, чтобы его значение было симметрично относительно центральной линии.
<img width=600 src=https://user-images.githubusercontent.com/54934129/90952413-fe75fb80-e46b-11ea-8ffe-d99ab63138e8.jpeg>

4. Значение порядка используется в качестве `offset` на этапе рендеринга слоя метро.

@tomilov @darina В чем состоял баг, когда линии при описанном подходе почему-то все равно накладывались друг на друга или находились на не равном расстоянии друг от друга: я не учитывала, что некоторые отрезки могут совпадать, но иметь противоположную направленнсть. Для них значение order нужно умножать на -1. Пример: есть сегмент `ABCDEFG` линии 1, и есть сегмент `TTEDCT` линии 2. У них идут параллельно отрезки `CDE` и `EDC` соответственно. Но направление `EDC` противоположно направлению `CDE`, и если мы присвоим отрезкам смещение -1 и 1, то они будут наложены друг на друга. А если -1 и -1, то будут идти рядом параллельно. Потому что смещение отсчитывается от самой линии, и ее направленность имеет значение.

**2. Отсеивать для п.1 "укороченные сплайны": они не должны быть отрисованы на схеме метро.**
Откуда взялись укороченные линии, можно посмотреть в Дашином докладе (ссылка с временной меткой):
https://youtu.be/oODvvV0_7rk?t=481

Отсеивание укороченных сплайнов для схемы теперь вынесено в офлайн. Они не попадают в lines_metadata.transit.json. Методы для нахождения исходной линии для укороченной: `GetParentLineForSpline(lineId)`, `GetSplineParent(lineId, region)`.

**3. Исправлена логика добавления остановок и пересадок в mwm:** раньше был баг, из-за которого линии, вылезающие за границы mwm, мы добавляли целиком (а не обрезали до "соседней" по ту сторону границы остановки), а некоторые остановки за пределами границы - наоборот не добавляли. Для решений этой проблемы добавлен метод `GetStopsRange( lineStopIds, stopIdsInRegion)`, и исправлен метод `SplitLinesBasedData()`.

2020-09-29 15:48 UTC, mesozoic-drones commented
@maksimandrianov @tomilov PTAL

2020-09-29 15:48 UTC, mesozoic-drones commented
JTALL

2020-10-02 11:16 UTC, tomilov requested changes

2020-10-02 12:34 UTC, mesozoic-drones commented on drape_frontend/transit_scheme_builder.cpp
> +m2::PointD kDefaultDirection{0.5, 0.5};
Нет constexpr - мой косяк. Перенесла в анонимный namespace.

2020-10-02 12:55 UTC, mesozoic-drones commented on transit/world_feed/feed_helpers.cpp
> +    return (++distToIndexes.begin())->second;
В каких случаях это условие вообще выполняется: если одна и та же последовательность точек встречается в полилинии более 1 раза. Иными словами, некоторые отрезки полилинии накладываются друг на друга. Теоретический пример наложения (в ОСМ Осло замаплен по другому, так что перехлеста нет):
![ff729e5f8c3d316b42b8a801265ddc8d](https://user-images.githubusercontent.com/54934129/94925224-8a496180-04c7-11eb-8225-5c6aa43c1c98.png)

В метро всего мира такое наложение возможно максимум 1 раз, то есть "двойных" петель в мапинге ОСМа пока нет. 

Но ты правильно заметил, теоретически они могут нагенериться. Поэтому добавила чек.

2020-10-02 12:56 UTC, mesozoic-drones commented on transit/world_feed/subway_converter.cpp
> +    return (++distToIndexes.begin())->second;
У тебя продублировались комменты, ответ здесь:
https://github.com/mapsme/omim/pull/13592#discussion_r498803292

2020-10-05 11:44 UTC, maksimandrianov commented on transit/world_feed/subway_converter.cpp
> +        continue;
{}

2020-10-05 11:45 UTC, maksimandrianov commented on transit/world_feed/subway_converter.cpp
> +        linksForRemoval.push_back(shapeLink);
{}

2020-10-05 11:46 UTC, maksimandrianov commented on transit/world_feed/subway_converter.cpp
> +      it->second.erase(sl);
еще есть версия erase, которая принимает итераторы начала и конца

2020-10-05 13:32 UTC, mesozoic-drones commented
@maksimandrianov @tomilov Чтобы прояснить отдельные моменты в реквесте)

Обзорная схема сущностей ОТ, с которыми идет работа в рантайме приложения, которые для этого подготавливаются генератором, а перед этим - подготавливаются gtfs_converter'ом:

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/54934129/95084458-9848ed80-0726-11eb-95c6-74a466704ea9.png">

### Описание сущностей, участвующих в этом реквесте
**shapes** - это геометрия линии маршрута. Полилиния, к которой привязан айди. На shape через shapeLink могут ссылаться линии целиком (lines) и отдельные ребра (edges) линий. shapeLink - это айди полилинии и индексы начала и конца на ее векторе точек.

**routes** - маршруты ОТ. Важные свойства маршрута - название, цвет и набор линий (lines).

**lines** - линии маршрута. Кроме "туда-обратно" есть экзотические варианты типа "все остановки в одну сторону кроме одной". Для таких линий наш питоновский скрипт подготовки json'а метро генерит укороченные сплайны. А в этом реквесте они отсеиваются, чтобы не попасть в lines metadata.

**lines_metadata** - айди линий и список сегментов на ее shape со смещениями. Это инфа, нужная, чтобы красиво отобразить линию на схеме метро. Соответственно не каждая линия может попасть в lines_metadata: только то, что должно быть отрендерено на слое метро. И только не укороченные сплайны. Дубли геометрии тоже отсеиваются (например, линии туда-обратно).

2020-10-05 13:40 UTC, mesozoic-drones commented
Пример элемента в lines_metadata:
```json
{
  "id": 11736768,
  "shape_segments": [
    {
      "order": 0,
      "start_index": 0,
      "end_index": 495
    },
    {
      "order": 0,
      "start_index": 495,
      "end_index": 594
    },
    {
      "order": -1,
      "start_index": 594,
      "end_index": 792
    },
    {
      "order": 0,
      "start_index": 792,
      "end_index": 891
    },
    {
      "order": -1,
      "start_index": 891,
      "end_index": 990
    },
    {
      "order": 0,
      "start_index": 990,
      "end_index": 1089
    },
    {
      "order": 0,
      "start_index": 1089,
      "end_index": 1188
    },
    {
      "order": 0,
      "start_index": 1188,
      "end_index": 1287
    },
    {
      "order": 0,
      "start_index": 1287,
      "end_index": 1386
    },
    {
      "order": -1,
      "start_index": 1386,
      "end_index": 1485
    },
    {
      "order": 0,
      "start_index": 1485,
      "end_index": 1782
    },
    {
      "order": 0,
      "start_index": 1782,
      "end_index": 2178
    },
    {
      "order": 0,
      "start_index": 2178,
      "end_index": 2574
    },
    {
      "order": 0,
      "start_index": 2574,
      "end_index": 2673
    },
    {
      "order": 0,
      "start_index": 2673,
      "end_index": 2871
    },
    {
      "order": -1,
      "start_index": 2871,
      "end_index": 3267
    }
  ]
}
```

Он означает, что линия с айди 11736768 состоит из 16 отрезков. На отрезке полилинии с индекса 0 до 495 у нее смещение 0. А например на отрезке [2871, 3267] (это последний элемент в массиве) - смещение -1 относительно оси симметрии линии. То есть на этом участке при отрисовке она смещена влево, если смотреть по направлению от начала до конца. Если было бы "2" - то на 2 пункта вправо и тд.

2020-10-06 07:26 UTC, maksimandrianov commented on transit/world_feed/feed_helpers.cpp
> +std::pair<size_t, size_t> FindPointsIndexes(std::vector<m2::PointD> const & shape,
название функции не очень хорошо отражает происходящее внутри
может добавить какое-то прилагательное? индексы каких точек?

2020-10-06 07:38 UTC, maksimandrianov commented on transit/world_feed/feed_helpers.cpp
> +  std::vector<size_t> const & indexes1 = GetMinDistIndexes(shape, p1);
если сделать 
```
return FindPointsIndexes(shape, std::vector<m2::PointD>{p1, p2});
```
то будет другой смысл?

2020-10-06 07:41 UTC, maksimandrianov commented on transit/world_feed/feed_helpers.cpp
> +  std::vector<size_t> const & indexes1 = GetMinDistIndexes(shape, p1);
если да, то на мой взгляд лучше изменить название функции

2020-10-06 07:55 UTC, maksimandrianov commented on transit/world_feed/subway_converter.cpp
> +    if (routeToStops.size() < 2)
фильтруем какие-то мусорные объекты?

2020-10-06 07:59 UTC, maksimandrianov commented on transit/world_feed/subway_converter.hpp
> +  // We try to minimize the reversed lines count.
Tries to minimize the reversed lines count.
?

2020-10-06 08:05 UTC, maksimandrianov commented on transit/world_feed/subway_converter.hpp
> +  void MirrorReversedLines();
мб MirrorReversedLines -> MinimizeReversedLinesCount

2020-10-06 08:10 UTC, maksimandrianov commented on transit/world_feed/world_feed.cpp
> +    lineData.m_shapeLink.m_endIndex = m_shapes.m_data[lineData.m_shapeId].m_points.size() - 1;
не может быть ...size() == 0 и ..Index = -1?
вопрос и про два случая выше

2020-10-06 09:29 UTC, mesozoic-drones commented on transit/world_feed/subway_converter.cpp
> +      it->second.erase(sl);
ага, но здесь она не подходит, потому что у нас нет заданного интервала "от-до", а есть отдельные элементы.

2020-10-06 09:37 UTC, mesozoic-drones commented on transit/world_feed/subway_converter.cpp
> +    if (routeToStops.size() < 2)
Добавила комментарий: нет, это не мусроные пересадки. Это "пересадки" между линиями на одном и том же маршруте. 

В старой версии они были нужны, так как мы рисовали параллельные линии одного и того же маршрута. Теперь мы рисуем только параллельные линии разных маршрутов, и считаем, что внутри одного и того же маршрута не может быть пересадок (фактически так и есть). 

Пример: нельзя сказать, что станция Митино на синей ветке московского метро связана пересадкой со станцией Митино =)) Это одна и та же станция одного и того же маршрута. Просто на ней стыковка [зонного оборота поездов,](https://ru.wikipedia.org/wiki/Арбатско-Покровская_линия#Зонный_оборот_поездов) поэтому старая версия считает станцию пересадкой.

2020-10-06 09:41 UTC, mesozoic-drones commented on transit/world_feed/world_feed.cpp
> +    lineData.m_shapeLink.m_endIndex = m_shapes.m_data[lineData.m_shapeId].m_points.size() - 1;
Точно не может быть. Для спокойствия добавила чек.

2020-10-06 10:01 UTC, mesozoic-drones commented on transit/world_feed/feed_helpers.cpp
> +std::pair<size_t, size_t> FindPointsIndexes(std::vector<m2::PointD> const & shape,
Переименовала функцию. Суть такая: мы ищем точки p1 и p2 на полилинии shape. И той, и другой может быть встречено несколько штук. Мы возвращаем индексы ближайших друг к другу точек на полилинии. 
Упрощенный пример (вместо точек - целые числа):
`shape = [7, 2, 2, 9, 0, 2, 1, 6, 0]`

Ищем в `shape p1 = 6,  p2 = 2.`
Функция вернет `7, 6.`

2020-10-06 10:32 UTC, mesozoic-drones commented on transit/world_feed/feed_helpers.cpp
> +  std::vector<size_t> const & indexes1 = GetMinDistIndexes(shape, p1);
Заменила название с FindPointsIndexes  на FindPointsOnShape, теперь должно быть понятнее.

2020-10-07 12:00 UTC, maksimandrianov commented on transit/world_feed/subway_converter.cpp
> +  return static_cast<uint32_t>(lineId >> 4);
почему >> 4?

2020-10-07 12:12 UTC, maksimandrianov commented on transit/world_feed/world_feed.cpp
> +      m_splitting.m_stops[region].insert(id);
диапазонный инсерт?

2020-10-07 12:16 UTC, maksimandrianov approved these changes
LGTM

2020-10-07 12:20 UTC, mesozoic-drones commented on transit/world_feed/subway_converter.cpp
> +  return static_cast<uint32_t>(lineId >> 4);
Так исторически сложилось: сдвиг айди линии на 4 для определения айди маршрута заложен еще в питоновской тулзе `tools/transit/transit_graph_generator.py`

2020-10-07 12:48 UTC, maksimandrianov commented on transit/world_feed/subway_converter.cpp
> +  return static_cast<uint32_t>(lineId >> 4);
мб коммент с отсылкой к tools/transit/transit_graph_generator.py?

2020-10-08 07:16 UTC, mesozoic-drones commented
JTALL

2020-10-08 07:19 UTC, mesozoic-drones commented
@maksimandrianov @tomilov PrepareLinesMetadata() зарефакторен, стал покороче и попонятнее.

2020-10-08 19:06 UTC, tomilov requested changes

2020-10-08 19:06 UTC, tomilov commented on transit/world_feed/subway_converter.hpp
> +  static std::pair<TransitId, LineData> MakeLine(routing::transit::Line const & lineSubway,
Если функция не предполагается к использованию вне соотв. cpp, то `static` нужно указать в cpp, а это объявление удалить из хедера. Либо просто убрать этот `static`. Вряд ли ещё экспортируется символ `transit::MakeLine` где-либо.

2020-10-09 07:00 UTC, mesozoic-drones commented on transit/world_feed/feed_helpers.cpp
> +  bool firstStopIsSet = false;
Добавила функцию StopIndexIsSet(size_t stopIndex). Все проверки теперь через нее.

2020-10-09 07:04 UTC, mesozoic-drones commented on transit/world_feed/feed_helpers.cpp
> +  {
Чтобы добавить айди остановок в соседних мвм. Если линия маршрута целиком лежит в одной мвм, возвращается интервал остановок, геометрически также лежащих в этой мвм. Но если линия заходит в соседние мвм, то мы придерживаемся логики добавления остановок в мвм, реализованной в старой версии транзита:
- Добавляем в мвм остановку из соседней мвм.
- Чтобы не прерывать линию на границе мвм, продлеваем эту линию до добавленной остановки.

2020-10-09 07:16 UTC, mesozoic-drones commented on transit/world_feed/feed_helpers.cpp
> +    if (base::AlmostEqualAbs(dist, minDist, kEps))
Предлагаю этот фрагмент оставить как есть, потому что так он проще воспринимается. А в твоем ифе, чтобы абсолютно во всех случаях работать корректно, нужен еще fabs().

2020-10-09 07:22 UTC, mesozoic-drones commented on transit/world_feed/feed_helpers.cpp
> +    distToIndexes.emplace(minDist, std::make_pair(i1, i2));
Да, так сделано именно чтобы код был попроще. indexes1.size() и indexes2.size() - ага, это чаще всего 1, но в терминальных случаях 2-3.

2020-10-09 07:24 UTC, mesozoic-drones commented on transit/world_feed/world_feed_tests/world_feed_tests.cpp
> +                 01 /* firstIdxPlan */, 4 /* lastIdxPlan */);
пофиксила)

2020-10-09 07:31 UTC, mesozoic-drones commented on transit/world_feed/subway_converter.cpp
> +  m2::PointD const startPoint = polyline[segment.m_startIdx];
Эти точки нужны не для задания сегмента. Они используются для определения, направлены ли параллельные участки линий в одну сторону или в противоположные:

```
        bool const codirectional =
            base::AlmostEqualAbs(linePart.m_firstPoint, parallelFirstPoint, kEps);
```

2020-10-09 07:32 UTC, mesozoic-drones commented on transit/world_feed/subway_converter.cpp
> +// consumption that this segment is reversed. Example: we have polyline [1, 2, 3, 4, 5, 6] and
спасибо))

2020-10-09 07:39 UTC, mesozoic-drones commented on transit/world_feed/subway_converter.hpp
> +  static std::pair<TransitId, LineData> MakeLine(routing::transit::Line const & lineSubway,
Закладываемся на то, что многие методы SubwayConverter захочется покрыть тестами.

2020-10-09 09:01 UTC, mesozoic-drones commented on transit/world_feed/subway_converter.cpp
> +      it->second[newShapeLink] = lineId;
В предыдущем реквесте мы обсуждали, что `container[k] = v` можно писать и для добавления новых элементов (у нас это встречается в разных частях проекта, и мне так кажется довольно удобно). Если не критично, я бы оставила.

2020-10-09 09:07 UTC, mesozoic-drones commented on transit/world_feed/subway_converter.cpp
> +    linePoints.emplace(lineSchemeData.m_shapeLink.m_startIndex, LinePointState());
А почему? Кажется, здесь и так и так нормально.

2020-10-09 09:14 UTC, mesozoic-drones commented
JTALL

2020-10-09 15:38 UTC, tomilov commented on transit/world_feed/subway_converter.hpp
> +  static std::pair<TransitId, LineData> MakeLine(routing::transit::Line const & lineSubway,
Какую роль в этом играет `static`?

2020-10-09 15:41 UTC, tomilov commented on transit/world_feed/subway_converter.cpp
> +    linePoints.emplace(lineSchemeData.m_shapeLink.m_startIndex, LinePointState());
Нормально, можно не исправлять. Здесь создаётся default-constructed объект и копируется в элемент `linePoints`. В случае `operator []` просто создаётся default-constructed объект. Практически ничего не значит.

2020-10-09 15:41 UTC, tomilov commented on transit/world_feed/subway_converter.cpp
> +      it->second[newShapeLink] = lineId;
OK

2020-10-09 15:42 UTC, tomilov commented on transit/world_feed/subway_converter.cpp
> +  m2::PointD const startPoint = polyline[segment.m_startIdx];
Вот и вскрылся уровень моего понимания того, что здесь происходит)).

2020-10-09 15:58 UTC, mesozoic-drones commented on transit/world_feed/feed_helpers.cpp
> +    if (base::AlmostEqualAbs(dist, minDist, kEps))
Да, но `minDist - kEps` теоретически же может быть < 0.

2020-10-09 16:05 UTC, mesozoic-drones commented on transit/world_feed/subway_converter.hpp
> +  static std::pair<TransitId, LineData> MakeLine(routing::transit::Line const & lineSubway,
static - просто говорит о том, что метод не привязан к экземпляру класса. А чем он тебя смущает?) У нас же много где так - если метод может быть статическим, то его в большинстве случаев делают статическим: в хедере указывают `static f()`, а в .cpp - по необходимости закомменченный` // static` , чтобы удобней было парсить глазами. Пример - в routing/astar_algorithm.hpp:372   `static void ReconstructPathBidirectional(...)`.

2020-10-09 16:06 UTC, tomilov commented on transit/world_feed/feed_helpers.cpp
> +    if (base::AlmostEqualAbs(dist, minDist, kEps))
В любом случае не настаиваю.

2020-10-09 16:10 UTC, tomilov commented on transit/world_feed/subway_converter.hpp
> +  static std::pair<TransitId, LineData> MakeLine(routing::transit::Line const & lineSubway,
Как в этом помогает `static`? Не могу придумать пример, когда namespace scope `static` уместен в хедере.

2020-10-09 16:11 UTC, tomilov commented on transit/world_feed/subway_converter.hpp
> +  static std::pair<TransitId, LineData> MakeLine(routing::transit::Line const & lineSubway,
сорян. Я проглядел, что это метод.

2020-10-09 16:12 UTC, tomilov commented on transit/world_feed/feed_helpers.cpp
> +    if (base::AlmostEqualAbs(dist, minDist, kEps))
> Да, но `minDist - kEps` теоретически же может быть < 0.

На корректность это не влияет.

2020-10-13 12:55 UTC, mesozoic-drones commented
JTALL

2020-10-13 13:06 UTC, ToshUxanoff commented
JTANDROID

2020-10-13 13:28 UTC, ToshUxanoff commented
JTANDROID

2020-10-13 13:31 UTC, ToshUxanoff commented
JTANDROID

2020-10-14 15:46 UTC, mesozoic-drones commented
JTALL

2020-10-16 13:19 UTC, mesozoic-drones commented
JTALL

2020-10-16 15:05 UTC, mesozoic-drones commented on transit/world_feed/world_feed_integration_tests/world_feed_integration_tests.cpp
> +    TEST_EQUAL(stopsInRegions["Switzerland_Ticino"].size(), 3, ());
В исходном варианте на карту не попадали остановки на линии, геометрически принадлежащие соседней mwm. А на самом деле должны, чтобы линии не обрывались в пустоту, а завершались этими ближайшими к границе (но со внешней стороны) остановками.

2020-10-16 15:06 UTC, mesozoic-drones commented on transit/world_feed/world_feed.cpp
> +    if(it == m_edgesOnShapes.end())
Это может быть, если данные - из GTFS, а не из нашего json'а метро.

2020-10-16 15:10 UTC, mesozoic-drones commented on transit/world_feed/subway_converter.cpp
> +  ConvertTransfers();
Раньше convertTransfers заполнял пересадки по старому принципу, по которому пересадка может быть и внутри одного маршрута (условно переход с "библиотеки имени ленина" на нее же, с красной на красную). Теперь мы такие точки не считаем пересадками, и теоретически обычных пересадок между разными линиями может не быть. И это справедливо даже для метро из многих линий: остановка просто будет принадлежать всем этим линиям, будут существовать соответствующие ребра.

2020-10-16 15:11 UTC, tomilov commented on transit/world_feed/world_feed.cpp
> +    if(it == m_edgesOnShapes.end())
Спасибо.

2020-10-16 15:12 UTC, tomilov commented on transit/world_feed/world_feed_integration_tests/world_feed_integration_tests.cpp
> +    TEST_EQUAL(stopsInRegions["Switzerland_Ticino"].size(), 3, ());
Спасибо!

2020-10-16 15:14 UTC, tomilov approved these changes

2020-10-16 15:14 UTC, merged