[catalog] send up to 30 guides ids into X-Mapsme-Downloaded-Guides he…
mapsme/omim pull request #13794
Opened 2020-10-08 16:51 UTC by milchakov

…ader only.

https://jira.mail.ru/browse/MAPSME-14641

2020-10-09 14:28 UTC, tomilov requested changes

2020-10-09 14:28 UTC, tomilov commented on map/bookmark_manager.cpp
> +  return GetCategoriesFromCatalog([](kml::AccessRules accessRules) {
Скобочка.

2020-10-09 14:28 UTC, tomilov commented on map/catalog_headers_provider.cpp
> +      std::mt19937 generator(device());
Опционально. Эта штука весит 2.5кб на стеке. И потенциально инициализируется небыстро каждый раз. Может быть сделать её `static std::mt19937 generator(std::random_device{}());`? Ещё сталкивался с тем, что `std::random_device` даёт константу на некоторых платформах. Т.е. seed может каждый раз быть одним и тем же, что приведёт к отсутствию случайности, а `static` решил бы эту проблему.

2020-10-09 15:23 UTC, milchakov commented on map/catalog_headers_provider.cpp
> +      std::mt19937 generator(device());
тоже сомневался до последнего. сделаю обычный srand + rand. что думаешь?

2020-10-09 15:30 UTC, milchakov commented on map/catalog_headers_provider.cpp
> +      std::mt19937 generator(device());
а, с с++17 так нельзя теперь...((

2020-10-09 15:30 UTC, milchakov commented on map/catalog_headers_provider.cpp
> +      std::mt19937 generator(device());
окей, тогда статик

2020-10-09 15:31 UTC, milchakov commented on map/catalog_headers_provider.cpp
> +      std::mt19937 generator(device());
спасибо

2020-10-09 15:32 UTC, milchakov commented on map/bookmark_manager.cpp
> +  return GetCategoriesFromCatalog([](kml::AccessRules accessRules) {
готово

2020-10-09 15:43 UTC, milchakov commented
@tomilov PTAL

2020-10-09 16:24 UTC, tomilov approved these changes

2020-10-09 16:25 UTC, tomilov commented
@milchakov rebase on top of master please

2020-10-12 07:47 UTC, milchakov commented
готово @tomilov

2020-10-12 18:13 UTC, merged