[bookmarks] helper methods for compilations
mapsme/omim pull request #13816
Opened 2020-10-14 17:21 UTC by milchakov

@Polas fyi

2020-10-14 17:25 UTC, Polas commented
По коду не совсем понятно что вернется для рутового categoryId

2020-10-15 07:51 UTC, milchakov commented
ок, какие предложения? переименовать Compilation -> Child ?

2020-10-15 08:24 UTC, Polas commented
> ок, какие предложения? переименовать Compilation -> Child ?

Я имел ввиду состав энума CompilationType, там сейчас 3 кейса: Category, Collection, Day. Поэтому у меня вопрос, что будет если передать в метод GetCompilationType рутовый айдишник? По стате он должен вернуть что-то вроде Main, но по коду я понимаю что произойдет.

2020-10-15 08:33 UTC, milchakov commented
> > ок, какие предложения? переименовать Compilation -> Child ?
> 
> Я имел ввиду состав энума CompilationType, там сейчас 3 кейса: Category, Collection, Day. Поэтому у меня вопрос, что будет если передать в метод GetCompilationType рутовый айдишник? По стате он должен вернуть что-то вроде Main, но по коду я понимаю что произойдет. Получается нужно всегда проверять методом IsBookmarkCompilation ?

По задумке - да, проверять сначала IsBookmarkCompilation. Так как енум содержит значения только для дочерних групп, то родительскую туда некуда пихнуть. можно сделать 1 метод, который будет возвращать опшнл. Я изначально в чате предложил эти два метода, @velichkomarija ответила, что ее устраивает, от ios никто ничего не написал, поэтому я сделал так. Могу переделать на один метод, возвращающий опциональное значение, если вам так больше нравится.

2020-10-15 08:54 UTC, Polas commented
> > > ок, какие предложения? переименовать Compilation -> Child ?
> > 
> > 
> > Я имел ввиду состав энума CompilationType, там сейчас 3 кейса: Category, Collection, Day. Поэтому у меня вопрос, что будет если передать в метод GetCompilationType рутовый айдишник? По стате он должен вернуть что-то вроде Main, но по коду я понимаю что произойдет. Получается нужно всегда проверять методом IsBookmarkCompilation ?
> 
> По задумке - да, проверять сначала IsBookmarkCompilation. Так как енум содержит значения только для дочерних групп, то родительскую туда некуда пихнуть. можно сделать 1 метод, который будет возвращать опшнл. Я изначально в чате предложил эти два метода, @velichkomarija ответила, что ее устраивает, от ios никто ничего не написал, поэтому я сделал так. Могу переделать на один метод, возвращающий опциональное значение, если вам так больше нравится.

Опциональное значение делать не надо. Я предположил что вложенность можно полностью покрыть одним энумом. Ладно с отдельным методом ок.

2020-10-15 09:35 UTC, tomilov requested changes

2020-10-15 09:35 UTC, tomilov commented on map/bookmark_manager.cpp
> +bool BookmarkManager::IsBookmarkCompilation(kml::MarkGroupId id) const
В структуре данных `kml::CategoryData` могут быть и треки. Если вдруг из задействуют в компиляциях, то придётся переименовывать в `IsCompilation`. Тем более в других местах имена менее конкретные -- не содержат уточнения compilation чего именно.

2020-10-15 13:16 UTC, milchakov commented on map/bookmark_manager.cpp
> +bool BookmarkManager::IsBookmarkCompilation(kml::MarkGroupId id) const
переименовал

2020-10-15 13:16 UTC, milchakov commented
@tomilov @velichkomarija  PTAL

2020-10-15 13:26 UTC, tomilov approved these changes

2020-10-15 13:44 UTC, velichkomarija approved these changes

2020-10-15 13:44 UTC, merged