Citymobil category
mapsme/omim pull request #13830
Opened 2020-10-16 16:39 UTC by milchakov

https://jira.mail.ru/browse/MAPSME-15065

2020-10-16 21:34 UTC, beloal commented on iphone/CoreApi/CoreApi/Search/MWMSearchFrameworkHelper.mm
> +    return [NSURL URLWithString:@("")];;
Я бы сделал этот метод nullable и возвращал здесь nil. Я не уверен что если инициализировать NSURL пустой строкой, absoluteString всегда будет пустой

2020-10-18 20:11 UTC, milchakov commented on iphone/CoreApi/CoreApi/Search/MWMSearchFrameworkHelper.mm
> +    return [NSURL URLWithString:@("")];;
Так и сделал сначала, но не вспомнил случаев в айос, чтоб использовался nil, по-этому вернул на пустой урл, думал вы всегда предпочитаете non-null. Окей, переделаю

2020-10-19 06:32 UTC, milchakov commented
@beloal PTAL

2020-10-19 06:47 UTC, milchakov commented
JTALL

2020-10-19 10:40 UTC, beloal requested changes

2020-10-19 10:40 UTC, beloal commented on iphone/CoreApi/CoreApi/Search/MWMSearchFrameworkHelper.h
> +- (nullable NSURL *)citymobilBannerUrl;
Нужно все вернуть как было и в этой строчке написать nullable
nullable в коде имеет приоритет над NS_ASSUME_NONNULL_BEGIN

2020-10-19 10:43 UTC, milchakov commented on iphone/CoreApi/CoreApi/Search/MWMSearchFrameworkHelper.h
> +- (nullable NSURL *)citymobilBannerUrl;
Окей. Но только становится менее читабельно - открываешь хедер - видишь, что написано, что все тут non-null, начинаешь читать объявления методов - оказывается, что есть один nullable.

2020-10-19 10:48 UTC, beloal commented on iphone/CoreApi/CoreApi/Search/MWMSearchFrameworkHelper.h
> +- (nullable NSURL *)citymobilBannerUrl;
NS_ASSUME_NONNULL_BEGIN означает что nonnull по-умолчанию, а не то что все nonnull

2020-10-19 11:25 UTC, milchakov commented on iphone/CoreApi/CoreApi/Search/MWMSearchFrameworkHelper.h
> +- (nullable NSURL *)citymobilBannerUrl;
готово

2020-10-19 11:26 UTC, milchakov commented
@beloal PTAL

2020-10-19 11:27 UTC, beloal approved these changes

2020-10-19 12:01 UTC, alexzatsepin approved these changes
Android LGTM

2020-10-19 12:01 UTC, alexzatsepin commented on android/src/com/mapswithme/maps/search/PromoCategory.java
> +          return "MEGAFON";
Наверное можно избавится, в принципе от этого мембера (getKey()) и вместо него использовать promo.name(). Но, возможно с мембером гибче и понятнее. Опционально.

2020-10-19 13:51 UTC, milchakov commented on android/src/com/mapswithme/maps/search/PromoCategory.java
> +          return "MEGAFON";
Я пытался вспомнить название метода, но что-то так и не вспомнил и подумал, что его совсем нету. Спасибо, заменю.

2020-10-19 13:55 UTC, milchakov commented on android/jni/com/mapswithme/maps/Framework.cpp
> +  auto const pos = frm()->GetCurrentPosition();
Думаю что нет. Я ориентировался на опыт с баннерами на диалоге загрузки карты. Сначала там так и делал, но потом появились некоторые партнеры, кому не важно расположение пользователя и все равно пришлось прокидывать опциональное значение.

2020-10-19 13:56 UTC, milchakov commented on android/jni/com/mapswithme/maps/Framework.cpp
> +  auto const pos = frm()->GetCurrentPosition();
ответил выше. с точки зрения кода пустое значение корректно обрабатывается в GetSearchCategoryBanners.

2020-10-19 15:42 UTC, tomilov requested changes

2020-10-19 15:42 UTC, tomilov commented on android/jni/com/mapswithme/maps/Framework.cpp
> +                               banners.begin()->m_type == ads::Banner::Type::Citymobil);
`s/begin()->/.front()./` (в любом случае - на твой вкус)

2020-10-19 15:42 UTC, tomilov commented on map/CMakeLists.txt
> +  ads_engine_delegate.hpp
В xcode не добавлено в этом коммите, а только два коммита спустя. Коммит несамодостаточный. Или это норм? Как принято? Главное, чтобы pr был самодостаточный?

2020-10-20 07:31 UTC, milchakov commented on map/ads_engine_delegate.cpp
> +                                             promo::Api const & promoApi, Purchase const & purchase,
а что не так? вроде в 100 умещается. или ты предлагаешь каждый параметр на новой строке? сейчас перенесу

2020-10-20 07:33 UTC, milchakov commented on android/jni/com/mapswithme/maps/Framework.cpp
> +                               banners.begin()->m_type == ads::Banner::Type::Citymobil);
да, что-то из головы вылетело, заменил

2020-10-20 08:18 UTC, tomilov commented on map/ads_engine_delegate.cpp
> +                                             promo::Api const & promoApi, Purchase const & purchase,
по скобочке должны быть

2020-10-20 08:21 UTC, milchakov commented on map/CMakeLists.txt
> +  ads_engine_delegate.hpp
Кажется, общего правила тут нет. Попробую порассуждать. У нас есть пару рекомендаций, которые могут конфликтовать друг с другом - это рекомендация делать модульные коммиты и рекомендация компилируемости приложения с любого коммита. В данном случае я предпочел сделать модульные коммиты для того чтобы ревьюверам было удобно смотреть свои платформы. Для сохранения требования компилируемости можно заливать реквесты в режиме squash & merge. На практике получается так, что все коммиты из этого реквеста атомарно заливаются в репозиторий, ядро компилируется и работает после ядрового коммита, платформы из соответствующих платформенных. Не могу с ходу представить задачу, при которой нужно собрать ios, но при этом не используя ui коммит для айос, а только ядровой. Для отладки кода из ядрового коммита достаточно тестов, которые будут успешно запускаться на ядровом коммите.

2020-10-20 08:22 UTC, tomilov commented on map/CMakeLists.txt
> +  ads_engine_delegate.hpp
Спасибо. Примерно так и думал.

2020-10-20 08:26 UTC, milchakov commented on map/ads_engine_delegate.cpp
> +                                             promo::Api const & promoApi, Purchase const & purchase,
а, точно, не заметил, спасибо

2020-10-20 09:19 UTC, milchakov commented
@tomilov PTAL

2020-10-20 09:33 UTC, tomilov commented on map/ads_engine_delegate.hpp
>                          storage::Storage const & storage, promo::Api const & promoApi,
И здесь отступы.

2020-10-20 09:46 UTC, milchakov commented on map/ads_engine_delegate.hpp
>                          storage::Storage const & storage, promo::Api const & promoApi,
спасибо. неправильно кланг-формат вызывал...

2020-10-20 09:46 UTC, milchakov commented
@tomilov PTAL

2020-10-20 10:07 UTC, tomilov approved these changes

2020-10-20 10:07 UTC, merged