[android] Replaced layers icons.
mapsme/omim pull request #13927
Opened 2020-11-05 16:15 UTC by velichkomarija

https://jira.mail.ru/browse/MAPSME-13741

2020-11-06 09:11 UTC, alexzatsepin requested changes

2020-11-06 09:11 UTC, alexzatsepin commented on android/res/values/themes-base.xml
> -    <item name="isoLinesMenuDisabled">@drawable/ic_planning_route_isomaps_light_on</item>
Все старые иконки нужно удалить из ресурсов.

2020-11-06 09:11 UTC, alexzatsepin commented on android/src/com/mapswithme/maps/maplayer/BottomSheetItem.java
> +  private final int mEnabledStateDrawableNightResId;
Маша, давай уберем это поле. А добавим еще один аттрибут по аналогии c ...MenuDisabled, только теперь это будут ..MenuEnabled, чтобы можно было только в theme-base.xml задать для них разные значения для ночной и дневной темы. И в методах makInstance доставай этот аттрибут из темы по аналогии с disabled, пожалуйста.

2020-11-06 09:58 UTC, velichkomarija commented on android/res/values/themes-base.xml
> -    <item name="isoLinesMenuDisabled">@drawable/ic_planning_route_isomaps_light_on</item>
Fixed

2020-11-06 09:58 UTC, velichkomarija commented on android/src/com/mapswithme/maps/maplayer/BottomSheetItem.java
> +  private final int mEnabledStateDrawableNightResId;
Да, исправила, так выглядит намного лучше

2020-11-06 11:57 UTC, alexzatsepin approved these changes

2020-11-09 06:33 UTC, velichkomarija commented on android/src/com/mapswithme/maps/maplayer/BottomSheetItem.java
> +      return new Subway(enabled, disabled);
Да, Леша, спасибо, при расширении до 3-х состояний мигрирую на селекторы, буду держать в голове.

2020-11-09 06:56 UTC, alexeyosminin approved these changes

2020-11-09 06:56 UTC, merged