Send navigation event broadcasts to external apps
mapsme/omim pull request #4427
Opened 2016-10-03 00:22 UTC by eigenein

Hi,

For Android developers (particularly for me) it might be useful to display navigation info on a custom device like a smartwatch. With this change one will be able to subscribe to navigation events with `BroadcastReceiver` and forward them anywhere.

Note: I didn't manage to find any source for `nativeGetDistanceAndAzimuthFromLatLon` so I suppose that `north = 0.0` provides me with real azimuth (i.e. relative to the North).

2016-10-03 11:40 UTC, Zverik commented
Could you please run `clang-format` on your code, and sign [the CLA](http://maps.me/cla/)?

2016-10-04 09:54 UTC, eigenein commented
Done!

2016-10-04 12:22 UTC, Zverik commented
@alexzatsepin это тебе? :)

2016-10-05 05:39 UTC, burivuh commented
Hi, we'll return to this PR during next week, ok? We're very interested in it, but there's a lack of time.

2016-10-05 10:50 UTC, eigenein commented
Привет! Да, не проблема. )

2016-10-18 07:32 UTC, alexzatsepin commented
1. Добавь, пожалуйста, эту схему https://www.dropbox.com/s/b6xbx5ajryh7rhx/maps.me.xml?dl=0 в AndroidStudio и с помощью нее отформатируй Java код (NavigationBroadcastController.java)

2016-10-18 07:33 UTC, alexzatsepin commented
@bykoianko PTAL please at first comment about `nativeGetDistanceAndAzimuthFromLatLon`

2016-10-18 07:54 UTC, alexzatsepin requested changes

2016-10-18 07:54 UTC, alexzatsepin commented on android/src/com/mapswithme/maps/routing/NavigationBroadcastController.java
> +    if (info == null) {
Мы не ставим скобку , когда тело if'а одна строчка

```
if (info == null) 
  return;
```

2016-10-18 07:54 UTC, alexzatsepin commented on android/src/com/mapswithme/maps/routing/NavigationBroadcastController.java
> +  public static void sendUpdate(final Context context, final RoutingInfo info) {
Nullness аннотации

`@NonNull final Context context, @NonNull (or Nullable) final RoutingInfo info)`

2016-10-18 07:54 UTC, alexzatsepin commented on android/src/com/mapswithme/maps/routing/NavigationBroadcastController.java
> +    if (!TextUtils.isEmpty(info.nextStreet)) {
Скобку надо убрать

2016-10-18 07:54 UTC, alexzatsepin commented on android/src/com/mapswithme/maps/routing/NavigationBroadcastController.java
> +    }
тут тоже  скобки надо убарть

2016-10-18 07:54 UTC, alexzatsepin commented on android/src/com/mapswithme/maps/routing/NavigationBroadcastController.java
> +  private static void updatePedestrian(final Intent intent, final RoutingInfo info) {
Nullness аннотации пожалуйста

2016-10-18 07:54 UTC, alexzatsepin commented on android/src/com/mapswithme/maps/routing/NavigationBroadcastController.java
> +  public static void sendIsNavigating(final Context context, final boolean isNavigating) {
Nullness аннотации

2016-10-18 07:54 UTC, alexzatsepin commented on android/src/com/mapswithme/maps/routing/NavigationBroadcastController.java
> +  private static void updateVehicle(final Intent intent, final RoutingInfo info) {
Nullness аннотации

2016-10-18 07:54 UTC, alexzatsepin commented on android/src/com/mapswithme/maps/routing/NavigationBroadcastController.java
> +    if (info.vehicleNextTurnDirection.containsNextTurn()) {
лишние скобки

```
if (info.vehicleNextTurnDirection.containsNextTurn())
  intent.putExtra(EXTRA_NEXT_TURN_DIRECTION, info.vehicleNextTurnDirection.name());
```

2016-10-18 07:55 UTC, alexzatsepin commented
@mpimenov @bykoianko PTAL please

2016-10-26 14:19 UTC, eigenein commented
@alexzatsepin 

1. Сделаю (BTW это не то же самое, что `clang-format` в c5c52f0?)
1. Сделаю
1. Основная идея была не ограничиваться Wearable Features для Android и дать возможность пересылать уведомления, например, на умные часы под другими ОСями.

2016-10-27 07:42 UTC, alexzatsepin commented
@eigenein 

1. Не совсем. Java код все же лучше через студию отформатировать. Недавно в clang-format добавили Java, но я еще не пробовал насколько правильно там все форматируется. Я пока clang-format только для плюсового кода использую.
3. Хм, а это технически возможно да, чтоб часы не на андроиде принимали интенты андроидовские? Если да, то ок.  Главное, чтобы не было проблем с посылкой слишком частых интентов в систему, т.к. наверно в 90% случаев часов у пользователя не будет, а слать интенты будем всегда.

2016-10-28 16:08 UTC, mpimenov commented on android/src/com/mapswithme/maps/routing/NavigationBroadcastController.java
> +  private static double north;
s/north/mNorth/

2016-10-28 16:08 UTC, mpimenov commented on android/src/com/mapswithme/maps/routing/NavigationBroadcastController.java
> +  public static void setNorth(final double north) {
Скобки у нас в формате
{
}
везде

2016-10-28 16:08 UTC, mpimenov commented on android/src/com/mapswithme/maps/routing/NavigationBroadcastController.java
> +    if (Framework.nativeGetRouter() == Framework.ROUTER_TYPE_PEDESTRIAN) {
А если велосипедный?

2016-10-28 16:08 UTC, mpimenov commented on android/src/com/mapswithme/maps/routing/NavigationBroadcastController.java
> +    // North is passed as the separate extra.
s/the/a/

2016-12-16 12:13 UTC, alexzatsepin commented
@eigenein PTAL

2017-11-02 13:50 UTC, mapsmetest commented
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

2017-11-14 13:42 UTC, mapsmetest commented
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

2017-11-23 11:33 UTC, mapsmetest commented
Jenkins asks: can anyone have a look at this request?
If you want Jenkins to compile and test this, write "test this please" or JT_TP (without the underscore in the middle).

2018-02-02 12:01 UTC, mapsmetest commented
Can one of the admins verify this patch?

2018-05-08 15:03 UTC, greshilov commented
Can one of the admins verify this patch?

2022-05-09 20:53 UTC, closed without merging